services:
  backend:
    image: kimminji1102/order-service:latest # docker hub에 push한 이미지 이름
    ports:
      - "80:80"
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'