server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?serverTimezone=Asia/Seoul
    username: root
    password: aaaa1111!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  cloud:
    aws:
      credentials:
        accessKey: AKIA3CMCCMMK6LCW73MG
        secretKey: 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
      region:
        static: ap-northeast-2
      s3:
        bucket: orderservice-prod-img9460

jwt:
  expiration: 30
  secretKey: +Wpu19RQrd9GaG41rBWlQuObyi9Ac/NiHfciyH0CNrNh8USmoVGFYy2ik2NH0q+wEEZ05Ir4JQcspuQ96yJQAA==
  expirationRt: 14400
  secretKeyRt: vlkWoV6DWP02+VvsVaje2Nbie1MVQL3TJwIgWHtCM6sGlK8Bg+CmIPRKZsga2ptnFreGdyeJz4+Hv/xiKQbzgw==